config/routes.rb
EventCircle::Application.routes.draw do

  devise_for :users, controllers: { sessions: "users/dash_board" }

   devise_scope :user do
         get '/home' => "devise/sessions#new", :as => :new_user_session
         post '/dash_board' => 'users/dash_board#create', :as => :user_session
         get '/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session

  end
  match  '/about_us'   => "home#about", as: :about_us

  resources :events do
    member do
      get 'register'
      get 'publish'
    end
  end
  root :to => 'home#index'
 

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :host
        can :manage, Event, :user_id => user.id
        can :read, Event
      else user.has_role? :guest
        can :read, Event
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
   belongs_to :user, :polymorphic => true
	belongs_to :addressable, polymorphic: true
   attr_accessible :address, :zipcode, :website, :phone_no
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	belongs_to :register, class_name: "Event"
	has_and_belongs_to_many :registered_users, :class_name => 'User', :join_table => :events_users, :association_foreign_key => :user_id,:uniq =>true
   attr_accessible :title, :description, :venue, :published, :published_at, :event_start_date, :event_end_date, :user_id
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

   has_one :address, as: :addressable
   #has_many :companies
   has_many :events
  has_and_belongs_to_many :registered_events, :class_name => 'Event', :join_table => :events_users, :association_foreign_key => :event_id,:uniq =>true
  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :uname,:email, :password, :password_confirmation, :remember_me, :mobile_no
  # attr_accessible :title, :body

  def is_registered?(event)
    registered_events.exists?(event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  before_filter :authenticate_user!
  def index
    @events = Event.where(published:true)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    @event.user=current_user
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
  def register
    @event = Event.find(params[:id])
    @event.registered_users << current_user

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'You Registered for a event successfully.' }
      format.json { head :no_content }
    end
  end

  def publish
    @event = Event.find(params[:id])
    @event.published = true
    @event.published_at = Time.now

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully published.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!, :only => :index
 
  def index
    @role = session[:role]
  	@events_attended = current_user.registered_events     
  	@events_published = Event.where(published: true)
      if @role =="host"
  	    @events_for_publish = current_user.events.where(published: false)
        @events_published_by_you = current_user.events.where(published: true)
      end
  end
  
  def about
  end

end

app/controllers/users/dash_board_controller.rb
class Users::DashBoardController < Devise::SessionsController
	
	def create
		if !params[:role].blank?
		  resource = warden.authenticate!(auth_options)
			if resource.has_role? params[:role]
			  session[:role] = params[:role]
			  super
			else
			  sign_out(resource_name)
			  redirect_to new_user_session_path,notice: "You are not authorized for this role" 
			end    
		  else		     
			redirect_to new_user_session_path,notice: " Please Select your Role" 
		  end
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/dash_board_helper.rb
module Users::DashBoardHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p id="notice"><%= notice %></p>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :event_start_date %><br />
    <%= f.datetime_select :event_start_date %>
  </div>
  <div class="field">
    <%= f.label :event_end_date %><br />
    <%= f.datetime_select :event_end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>
 <%= link_to t('.new', :default => t("helpers.links.sign_out")),
            destroy_user_session_path, :method => :delete,
            :class => 'btn pull-right btn-primary' %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Venue</th>
    <th>Event start date</th>
    <th>Event end date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.description %></td>
    <td><%= event.venue %></td>
    <td><%= event.event_start_date %></td>
    <td><%= event.event_end_date %></td>
    <% if can? :read, event %>
    <td><%= link_to 'Show', event %></td>
      <% if current_user.is_registered?(event) %>
        <td><%= link_to 'Registered', '#',class: "test"%></td>
      <% else %>
        <td><%= link_to 'Register', register_event_path(event)%></td>  
      <% end %>
    <% end %>
    <% if can? :edit, event %>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <% end %>
    <%if can? :delete, event %>
    <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<script>
 $(".test").click(function(){
  alert("registered")
 })
</script>
<%= link_to 'New Event', new_event_path %>
<%= link_to 'Back', root_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Venue:</b>
  <%= @event.venue %>
</p>

<p>
  <b>Event start date:</b>
  <%= @event.event_start_date %>
</p>

<p>
  <b>Event end date:</b>
  <%= @event.event_end_date %>
</p>

<% if can? :edit,@event %>
<%= link_to 'Edit', edit_event_path(@event) %> 
<% end %>
<%= link_to 'Back', events_path %>

app/views/home/about.html.erb

<%= render partial: "layouts/header"%>
		
<div class="clearfix"></div>
	<div class="banner-back">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
							<div class="about-box">
						<div class="about-box-head">
							<span class="title-2">About <span class="highlight-1">Us</span></span>
						</div>
						<div class="about-box-content">
						<p class="about-box-content">
						The complexity intrinsic in today’s events is growing exponentially. Meaningful, independent, third party validated data can make sense of this complexity and allow sponsors to choose events that will provide a sufficient ROI, making sponsorship a lucrative venture. Of importance in this regard is being able to utilize the data to differentiate between events and allow sponsorship of events to be dictated by pre-specified target demographic objectives and informed marketing decisions within industry segments. This will allow sponsors to feel confident about their investment, and allow for continued feedback as to what future sponsorship will prove valuable. 
						</p>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div> 
	
	<%= render partial: "layouts/content"%>

	
	<%= render partial: "layouts/footer"%>


app/views/home/index.html.erb
<%= render partial: "layouts/dash_board/header"%>

	<section>
	<div class="container-admin">
	<div class="row">
		<div class="col-custom-md-3">
			<div class="left-nav">
				<ul>
				<div class="selected"><li><%= link_to "Dash Board", events_path %></li></div>
				<li><a href="#">The EC</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Contact</a></li>
				</ul>
			</div>
		</div>
		<div class="col-custom-md-21">
			<div class="content-section">
			<h2 class="title">Dashboard</h2>
				<div class="some">
				<div class="header1 fixed" style ="float:left;margin:8px">
						<table class="table table-striped box-border table-dummy">
						   <thead class="box-head">
								  <tr><td colspan="3"><strong>Events <span style="color:#e06d21;">Registered</span></strong></td></tr>
								  
							</thead>
						
							<tbody>
							<tr>
									<td><strong>Title</strong></td>
									<td><strong>Venue</strong></td>
									<td><strong>Start Date</strong></td>
								</tr>
								<% @events_attended.to_enum.with_index(1) do |event,i |%>
								<tr>
									<td><%= event.title %></td>
									<td><%= event.venue %></td>
									<td><%= event.event_start_date %></td>
								</tr>
								<% break if i==3 %>
								<% end %>
						  </tbody>
						 </table>

						 <table class="table table-striped box-border table-main" style="display:none">
						   <thead class="box-head">
							  <tr>
								<tr><td colspan="6"><strong>Events <span style="color:#e06d21;">Registered</span></strong></td></tr>
							  </tr>
						   </thead>
						   <tbody>
							<tr>
									<td><strong>Title</strong></td>
									<td><strong>Venue</strong></td>
									<td><strong>Start Date</strong></td>
									<td><strong>End Date</strong></td>
									<td></td>
									<td></td>
								</tr>
								<% @events_attended.each do |event|%>
								<tr>
									<td><%= event.title %></td>
									<td><%= event.venue %></td>
									<td><%= event.event_start_date %></td>
									<td><%= event.created_at %></td>
									<% if can? :read, event %>
                                     <td><%= link_to 'Show', event %></td>
                                      <% if current_user.is_registered?(event) %>
                                     <td><%= link_to 'Registered', '#',class: "test"%></td>
                                   <% else %>
                                 <td><%= link_to 'Register', register_event_path(event)%></td>  
                                <% end %>
                                  <% end %>
								</tr>
								<% end %>
						  </tbody>
						 </table>

					</div>
					<div class="header1 fixed" style ="float:left;margin:8px">
						<table class="table table-striped box-border table-dummy">
						   <thead class="box-head">
							  <tr>
								<tr><td colspan="3"><strong>Events <span style="color:#e06d21;">Running</span></strong></td></tr>
							  </tr>
						   </thead>
						   <tbody>
							<tr>
									<td><strong>Title</strong></td>
									<td><strong>Venue</strong></td>
									<td><strong>Start Date</strong></td>
								</tr>
								<% @events_published.to_enum.with_index(1) do |event,i |%>
								<tr>
									<td><%= event.title %></td>
									<td><%= event.venue %></td>
									<td><%= event.event_start_date %></td>
								</tr>
								<% break if i==3 %>
								<% end %>
						  </tbody>
						 </table>


						 <table class="table table-striped box-border table-main" style="display:none">
						   <thead class="box-head">
							  <tr>
								<tr><td colspan="6"><strong>Events <span style="color:#e06d21;">Running</span></strong></td></tr>
							  </tr>
						   </thead>
						   <tbody>
							<tr>
									<td><strong>Title</strong></td>
									<td><strong>Venue</strong></td>
									<td><strong>Start Date</strong></td>
									<td><strong>End Date</strong></td>
									<td></td>
									<td></td>
								</tr>
								<% @events_published.each do |event|%>
								<tr>
									<td><%= event.title %></td>
									<td><%= event.venue %></td>
									<td><%= event.event_start_date %></td>
									<td><%= event.created_at %></td>
									<% if can? :read, event %>
                                     <td><%= link_to 'Show', event %></td>
                                      <% if current_user.is_registered?(event) %>
                                     <td><%= link_to 'Registered', '#',class: "test"%></td>
                                   <% else %>
                                 <td><%= link_to 'Register', register_event_path(event)%></td>  
                                <% end %>
                                  <% end %>
								</tr>
								<% end %>
						  </tbody>
						 </table>

					</div>
				</div> <!-- Row closing -->		


							<%if @role == "host"%>  <!-- for HOST -->
							<div class="some">
				<div class="header1 fixed" style ="float:left;margin:8px">
						<table class="table table-striped box-border table-dummy">
						   <thead class="box-head">
								  <tr><td colspan="3"><strong>Events <span style="color:#e06d21;">Published By You</span></strong></td></tr>
								  
							</thead>
						
							<tbody>
							<tr>
									<td><strong>Title</strong></td>
									<td><strong>Venue</strong></td>
									<td><strong>Start Date</strong></td>
								</tr>
							<% @events_published_by_you.to_enum.with_index(1) do |event,i |%>
								<tr>
									<td><%= event.title %></td>
									<td><%= event.venue %></td>
									<td><%= event.event_start_date %></td>
								</tr>
								<% break if i==3 %>
								<% end %>
						  </tbody>
						 </table>

						 <table class="table table-striped box-border table-main" style="display:none">
						   <thead class="box-head">
							  <tr>
								<tr><td colspan="6"><strong>Events <span style="color:#e06d21;">Published By You</span></strong></td></tr>
							  </tr>
						   </thead>
						   <tbody>
							<tr>
									<td><strong>Title</strong></td>
									<td><strong>Venue</strong></td>
									<td><strong>Start Date</strong></td>
									<td><strong>End Date</strong></td>
									<td></td>
									<td></td>
								</tr>
								<% @events_published_by_you.each do |event|%>
								<tr>
									<td><%= event.title %></td>
									<td><%= event.venue %></td>
									<td><%= event.event_start_date %></td>
									<td><%= event.created_at %></td>
									<% if can? :read, event %>
                                     <td><%= link_to 'Show', event %></td>
                                      <% if current_user.is_registered?(event) %>
                                     <td><%= link_to 'Registered', '#',class: "test"%></td>
                                   <% else %>
                                 <td><%= link_to 'Register', register_event_path(event)%></td>  
                                <% end %>
                                  <% end %>
								</tr>
								<% end %>
						  </tbody>
						 </table>

					</div>
					<div class="header1 fixed" style ="float:left;margin:8px">
						<table class="table table-striped box-border table-dummy">
						   <thead class="box-head">
							  <tr>
								<tr><td colspan="3"><strong>Events <span style="color:#e06d21;">Need To Publish</span></strong></td></tr>
							  </tr>
						   </thead>
						   <tbody>
							<tr>
									<td><strong>Title</strong></td>
									<td><strong>Venue</strong></td>
									<td><strong>Start Date</strong></td>
								</tr>
							<% @events_for_publish.to_enum.with_index(1) do |event,i |%>
								<tr>
									<td><%= event.title %></td>
									<td><%= event.venue %></td>
									<td><%= event.event_start_date %></td>
								</tr>
								<% break if i==3 %>
								<% end %>
						  </tbody>
						 </table>


						 <table class="table table-striped box-border table-main" style="display:none">
						   <thead class="box-head">
							  <tr>
								<tr><td colspan="6"><strong>Events <span style="color:#e06d21;">Need To Publish</span></strong></td></tr>
							  </tr>
						   </thead>
						   <tbody>
							<tr>
									<td><strong>Title</strong></td>
									<td><strong>Venue</strong></td>
									<td><strong>Start Date</strong></td>
									<td><strong>End Date</strong></td>
									<td></td>
									<td></td>
								</tr>
								<% @events_for_publish.each do |event|%>
								<tr>
									<td><%= event.title %></td>
									<td><%= event.venue %></td>
									<td><%= event.event_start_date %></td>
									<td><%= event.created_at %></td>
									<% if can? :read, event %>
                                     <td><%= link_to 'Show', event %></td>
                                <% if can? :update, event %>

                                <td><%= link_to 'Publish', publish_event_path(event)%></td>  
                                <% end %>
                                  <% end %>
								</tr>
								<% end %>
						  </tbody>
						 </table>

					</div>
				</div> <!-- Row closing -->		



				
							<% end %>



			<div class="clearfix"></div>
			</div> <!-- Content-section closing -->
		</div> <!-- Col-custom-21 closing -->
	</div><!-- Main Row closing -->	
    </div><!-- Container Admin closing -->	
	</section>
	
<style>

.fixed{
    width:45%;

}

.expand{
    width: 80%;
    height: 200px; 
        
}

</style>

<script>
$(document).ready(function(){
var a = 1;
$(".header1").click(function(){
	
	if(false==$(this).hasClass('expand')){

		$(".table-dummy").show();
	    $(".table-main").hide();
		$(this).children(".table-dummy").hide();
		$(this).children(".table-main").show();

$(".header1").addClass("fixed")
$(".header1").removeClass("expand")
$(this).addClass( "expand");

	}
		
});
});
</script>

app/views/layouts/_content.html.erb
	<div class="clearfix"></div>
	<div class="middle-bar">
		<div class="container">
			<div class="row">
				<div class="col-md-5 col-sm-5">
					<div class="title-1">Find or Register an Event Today.</div>
				</div>
				<div class="col-md-7 col-sm-7">
				<nav class="middle-nav">
					<ul>
						<li><a href="#">Host Event</a></li>
						<li><a href="#">Attend Event</a></li>
						<li><a href="#">Sponsor Event</a></li>
					</ul>
				</nav>
				</div>
			</div>
		</div>
	</div>
	
<div class="content-back">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="box">
						<div class="box-head">
							<span class="title-2">Event <span class="highlight-1">Host</span></span>
						</div>
						<div class="box-content">
						<p>
						Events today must balance the expectations and experiences of the guest with the limitations and proclivities of the host.  Increasingly complex needs and expectations are making the attainment of equilibrium somewhat elusive. Developing meaningful events that address these realities isn’t easy. For events to achieve lasting results and be considered worthy of future patronage, they must find a way to meet or exceed expectations. This makes knowing and accommodating expectations a competitive advantage and central for the success of an event. 
						</p>
						<p>Is your event organized in a way that can create meaningful results and accommodate the changing needs of both sponsors and guests? Do you want more engagement and connection before, during, and after the event? Do you want more people to know about your event? Do you want to create multiple events that run concurrently in support of an important cause? 
						</p>
						</p>
						The EC allows the host to have a deeper understanding of who their guests are and why they are attending their event.  It also creates the opportunity to maintain a connection with the guest before, during, and after the event. The event data available through the state of the art EC Assessment tool also allows hosts to better attract and work with sponsors, making sponsorship worthwhile throughout the event process.  
						</p>
						<p>
						<strong><a href="#" class="highlight-1">Learn More</a></strong>
						</p>
						</div>
					</div>
				</div>
			
				<div class="col-md-4">
					<div class="box">
						<div class="box-head">
							<span class="title-2">Event <span class="highlight-1">Guest</span></span>
						</div>
						<div class="box-content">
						<p>
						The amount of potential events a person can patronize is limitless. The information available to inform the patron of its efficacy with regard to them is often vague. Is it meaningful to you? Do you know what the event is all about and why it is important for you to attend that event at this stage of your life? Is there a vehicle in place to express any expectations you may have on the kind of experience you want to have before during and after the event? Does the event you are attending align with your goals? Check back with us and utilize The EC tool, which gives you comprehensive feedback informing you as to whether an event is appropriate for you at this time.
						</p>
						<p>
						<strong><a href="#" class="highlight-1">Learn More</a></strong>
						</p>
						</div>
					</div>
				</div>
			
			
			<div class="col-md-4">
					<div class="box">
						<div class="box-head">
							<span class="title-2">Event <span class="highlight-1">Sponsor</span></span>
						</div>
						<div class="box-content">
						<p>
						The complexity intrinsic in today’s events is growing exponentially. Meaningful, independent, third party validated data can make sense of this complexity and allow sponsors to choose events that will provide a sufficient ROI, making sponsorship a lucrative venture. Of importance in this regard is being able to utilize the data to differentiate between events and allow sponsorship of events to be dictated by pre-specified target demographic objectives and informed marketing decisions within industry segments. This will allow sponsors to feel confident about their investment, and allow for continued feedback as to what future sponsorship will prove valuable. 
						</p>
						<p>
Currently, there are conditions in the industry that impede the value sponsors gain from events. The EC helps sponsors access valuable data before, during, and after the event, allowing for an informed sponsorship decision. The state of the art EC Assessment Tool helps sponsors understand the important specifics of an event and allows the use of business analytics to determine whether the event is a worthy investment.  
						</p>
						<p>
						<strong><a href="#" class="highlight-1">Learn More</a></strong>
						</p>
						</div>
					</div>
			</div>
				
			</div>
		</div>
	</div>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset = "UTF-8">
<title>Event Circle - Dashboard</title>
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= stylesheet_link_tag 'home/mainpage/main-index'%>
</head>
<body>
	<header>
		<div class="container">
			<div class="row">
				<div class="col-md-5">
				<h1 class="tagline">Event Planning. Organizing. and Execution</h1>
				<img class="logo img-responsive" src="/assets/logo.jpg" alt="Logo"></img>
				</div>
				
				
				<div class="col-md-7">
					<div class="signup martop2">
						<form action="/dash_board" method="post" class="form-inline new_user" role="form" accept-charset="UTF-8"  id="new_user"  >

<div>
								<input name="utf8" type="hidden" value="&#x2713;" />
								<input name="authenticity_token" type="hidden" value="MD9N38/Jr8438i4QZv+ED5xUe8KMdtqWfZ2iAadZ5Ck=" />
							</div>

						  <div class="form-group">
                                                     <input type="email" name= 'user[email]'class="form-control" id="exampleInputEmail2" placeholder="Enter email">
						  </div>
						  <div class="form-group">
							<input type="password" name='user[password]' class="form-control" id="exampleInputPassword2" placeholder="Password">
						  </div>
						<select class="form-control" name ="role">
						  <option value="">Select</option>
						  <option value="guest">Guest</option>
						  <option value="host">Host</option>	
					          <option value="admin">Admin</option>
						</select>
						  <button type="submit" class="btn btn-default">Sign in</button>
						</form>
					</div>
					
					<!-- <div class="clearfix"></div> -->
					<nav class="main-nav">
						<ul class="nav-pills">
							<li><a href="#" class="selected">THE EC</a></li>
							<li><%= link_to "ABOUT",about_us_path %></li>
							<li><a href="#">REGISTER</a></li>
							<li><a href="#">CONTACT</a></li>
							<li><a href="#">EVENTS</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</header>
	

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>